[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags =
  -DARDUINO_ARCH_ESP32
  -DARDUINO_SDK_BOARD=ESP32-S3
lib_deps =
  bblanchon/ArduinoJson@^6.22.1
  wire
  adafruit/Adafruit MAX3010x Library@^1.0.0
  adafruit/Adafruit BusIO@^1.14.0
  
[platformio]
default_envs = esp32-s3
